### ISSUE TITLE
Username error.

### ISSUE THREAD

**Issue by Joshii01** [nfs-tech-bd/NFS-CLONE#1]
Hello there @nfs-tech-bd ! may i ask for the username please? i apparently need it for this to work.

**Comment by nfs-tech-bd** [comment]
@Joshii01 Hlw bro The Username is 
nfs-tech-bd
Password : nfs-clone
Follow me for more tools 🙂

**Comment by Joshii01** [comment]
Ok! thank you for your help :D

**Comment by sonil420** [comment]
What is password

**Comment by biplobhasan2070** [comment]
Already given
 The Username is
nfs-tech-bd
Password : nfs-clone
Follow me for more tools 🙂
